server:
  port: ${GP2GP_TRANSLATOR_SERVER_PORT:8085}

logging:
  level:
    uk.nhs.adaptors.pss.translator: ${LOG_LEVEL:INFO}

spring:
  datasource:
    url: ${PS_DB_URL:jdbc:postgresql://localhost:5436}/patient_switching
    username: gp2gp_user
    password: mlpMLP123qa

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

amqp:
  pss:
    queueName: ${PS_QUEUE_NAME:pssQueue}
    broker: ${PS_AMQP_BROKER:amqp://localhost:5672}
    username: ${PS_AMQP_USERNAME:}
    password: ${PS_AMQP_PASSWORD:}
    maxRedeliveries: ${PS_AMQP_MAX_REDELIVERIES:3}
  mhs:
    queueName: ${MHS_QUEUE_NAME:mhsQueue}
    broker: ${MHS_AMQP_BROKER:amqp://localhost:5672}
    username: ${MHS_AMQP_USERNAME:}
    password: ${MHS_AMQP_PASSWORD:}
    maxRedeliveries: ${MHS_AMQP_MAX_REDELIVERIES:3}

mhs:
  url: ${MHS_BASE_URL:http://localhost:8080}

storage:
  type: ${STORAGE_TYPE:LocalMock}
  region: ${STORAGE_REGION:}
  containerName: ${STORAGE_CONTAINER_NAME:}
  accountReference: ${STORAGE_REFERENCE:}
  accountSecret: ${STORAGE_SECRET:}



