server:
  port: ${GP2GP_SERVER_PORT:8085}

spring:
  datasource:
    url: ${PS_DB_URL:jdbc:postgresql://localhost:5436/patient_switching}
    username: gp2gp_user
    password: ${GP2GP_USER_DB_PASSWORD}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

amqp:
  pss:
    queueName: ${PSS_QUEUE_NAME:pssQueue}
    broker: ${PSS_AMQP_BROKER:amqp://localhost:5672}
    username: ${PSS_AMQP_USERNAME:}
    password: ${PSS_AMQP_PASSWORD:}
    maxRedeliveries: ${PSS_AMQP_MAX_REDELIVERIES:3}
  mhs:
    queueName: ${MHS_QUEUE_NAME:mhsQueue}
    broker: ${MHS_AMQP_BROKER:amqp://localhost:5672}
    username: ${MHS_AMQP_USERNAME:}
    password: ${MHS_AMQP_PASSWORD:}
    maxRedeliveries: ${MHS_AMQP_MAX_REDELIVERIES:3}
